export const countryCodes = [
  { country: 'India', label: '91', value: 91, countryCode: 'IN' },
  { country: 'United States', label: '1', value: 1, countryCode: 'US' },
  { country: 'Afghanistan', label: '93', value: 93, countryCode: 'AF' },
  { country: 'Aland Islands', label: '358', value: 358, countryCode: 'AX' },
  { country: 'Albania', label: '355', value: 355, countryCode: 'AL' },
  { country: 'Algeria', label: '213', value: 213, countryCode: 'DZ' },
  { country: 'American Samoa', label: '1684', value: 1684, countryCode: 'AS' },
  { country: 'Andorra', label: '376', value: 376, countryCode: 'AD' },
  { country: 'Angola', label: '244', value: 244, countryCode: 'AO' },
  { country: 'Anguilla', label: '1264', value: 1264, countryCode: 'AI' },
  { country: 'Antarctica', label: '672', value: 672, countryCode: 'AQ' },
  {
    country: 'Antigua and Barbuda',
    label: '1268',
    value: 1268,
    countryCode: 'AG',
  },
  { country: 'Argentina', label: '54', value: 54, countryCode: 'AR' },
  { country: 'Armenia', label: '374', value: 374, countryCode: 'AM' },
  { country: 'Aruba', label: '297', value: 297, countryCode: 'AW' },
  { country: 'Australia', label: '61', value: 61, countryCode: 'AU' },
  { country: 'Austria', label: '43', value: 43, countryCode: 'AT' },
  { country: 'Azerbaijan', label: '994', value: 994, countryCode: 'AZ' },
  { country: 'Bahamas', label: '1242', value: 1242, countryCode: 'BS' },
  { country: 'Bahrain', label: '973', value: 973, countryCode: 'BH' },
  { country: 'Bangladesh', label: '880', value: 880, countryCode: 'BD' },
  { country: 'Barbados', label: '1246', value: 1246, countryCode: 'BB' },
  { country: 'Belarus', label: '375', value: 375, countryCode: 'BY' },
  { country: 'Belgium', label: '32', value: 32, countryCode: 'BE' },
  { country: 'Belize', label: '501', value: 501, countryCode: 'BZ' },
  { country: 'Benin', label: '229', value: 229, countryCode: 'BJ' },
  { country: 'Bermuda', label: '1441', value: 1441, countryCode: 'BM' },
  { country: 'Bhutan', label: '975', value: 975, countryCode: 'BT' },
  {
    country: 'Bolivia, Plurinational State of bolivia',
    label: '591',
    value: 591,
    countryCode: 'BO',
  },
  {
    country: 'Bosnia and Herzegovina',
    label: '387',
    value: 387,
    countryCode: 'BA',
  },
  { country: 'Botswana', label: '267', value: 267, countryCode: 'BW' },
  { country: 'Bouvet Island', label: '47', value: 47, countryCode: 'BV' },
  { country: 'Brazil', label: '55', value: 55, countryCode: 'BR' },
  {
    country: 'British Indian Ocean Territory',
    label: '246',
    value: 246,
    countryCode: 'IO',
  },
  { country: 'Brunei Darussalam', label: '673', value: 673, countryCode: 'BN' },
  { country: 'Bulgaria', label: '359', value: 359, countryCode: 'BG' },
  { country: 'Burkina Faso', label: '226', value: 226, countryCode: 'BF' },
  { country: 'Burundi', label: '257', value: 257, countryCode: 'BI' },
  { country: 'Cambodia', label: '855', value: 855, countryCode: 'KH' },
  { country: 'Cameroon', label: '237', value: 237, countryCode: 'CM' },
  { country: 'Canada', label: '1', value: 1, countryCode: 'CA' },
  { country: 'Cape Verde', label: '238', value: 238, countryCode: 'CV' },
  { country: 'Cayman label', label: '345', value: 345, countryCode: 'KY' },
  {
    country: 'Central African Republic',
    label: '236',
    value: 236,
    countryCode: 'CF',
  },
  { country: 'Chad', label: '235', value: 235, countryCode: 'TD' },
  { country: 'Chile', label: '56', value: 56, countryCode: 'CL' },
  { country: 'China', label: '86', value: 86, countryCode: 'CN' },
  { country: 'Christmas Island', label: '61', value: 61, countryCode: 'CX' },
  {
    country: 'Cocos (Keeling) Islands',
    label: '61',
    value: 61,
    countryCode: 'CC',
  },
  { country: 'Colombia', label: '57', value: 57, countryCode: 'CO' },
  { country: 'Comoros', label: '269', value: 269, countryCode: 'KM' },
  { country: 'Congo', label: '242', value: 242, countryCode: 'CG' },
  {
    country: 'Congo, The Democratic Republic of the Congo',
    label: '243',
    value: 243,
    countryCode: 'CD',
  },
  { country: 'Cook Islands', label: '682', value: 682, countryCode: 'CK' },
  { country: 'Costa Rica', label: '506', value: 506, countryCode: 'CR' },
  { country: "Cote d'Ivoire", label: '225', value: 225, countryCode: 'CI' },
  { country: 'Croatia', label: '385', value: 385, countryCode: 'HR' },
  { country: 'Cuba', label: '53', value: 53, countryCode: 'CU' },
  { country: 'Cyprus', label: '357', value: 357, countryCode: 'CY' },
  { country: 'Czech Republic', label: '420', value: 420, countryCode: 'CZ' },
  { country: 'Denmark', label: '45', value: 45, countryCode: 'DK' },
  { country: 'Djibouti', label: '253', value: 253, countryCode: 'DJ' },
  { country: 'Dominica', label: '1767', value: 1767, countryCode: 'DM' },
  {
    country: 'Dominican Republic',
    label: '1849',
    value: 1849,
    countryCode: 'DO',
  },
  { country: 'Ecuador', label: '593', value: 593, countryCode: 'EC' },
  { country: 'Egypt', label: '20', value: 20, countryCode: 'EG' },
  { country: 'El Salvador', label: '503', value: 503, countryCode: 'SV' },
  { country: 'Equatorial Guinea', label: '240', value: 240, countryCode: 'GQ' },
  { country: 'Eritrea', label: '291', value: 291, countryCode: 'ER' },
  { country: 'Estonia', label: '372', value: 372, countryCode: 'EE' },
  { country: 'Ethiopia', label: '251', value: 251, countryCode: 'ET' },
  {
    country: 'Falkland Islands (Malvinas)',
    label: '500',
    value: 500,
    countryCode: 'FK',
  },
  { country: 'Faroe Islands', label: '298', value: 298, countryCode: 'FO' },
  { country: 'Fiji', label: '679', value: 679, countryCode: 'FJ' },
  { country: 'Finland', label: '358', value: 358, countryCode: 'FI' },
  { country: 'France', label: '33', value: 33, countryCode: 'FR' },
  { country: 'French Guiana', label: '594', value: 594, countryCode: 'GF' },
  { country: 'French Polynesia', label: '689', value: 689, countryCode: 'PF' },
  {
    country: 'French Southern Territories',
    label: '262',
    value: 262,
    countryCode: 'TF',
  },
  { country: 'Gabon', label: '241', value: 241, countryCode: 'GA' },
  { country: 'Gambia', label: '220', value: 220, countryCode: 'GM' },
  { country: 'Georgia', label: '995', value: 995, countryCode: 'GE' },
  { country: 'Germany', label: '49', value: 49, countryCode: 'DE' },
  { country: 'Ghana', label: '233', value: 233, countryCode: 'GH' },
  { country: 'Gibraltar', label: '350', value: 350, countryCode: 'GI' },
  { country: 'Greece', label: '30', value: 30, countryCode: 'GR' },
  { country: 'Greenland', label: '299', value: 299, countryCode: 'GL' },
  { country: 'Grenada', label: '1473', value: 1473, countryCode: 'GD' },
  { country: 'Guadeloupe', label: '590', value: 590, countryCode: 'GP' },
  { country: 'Guam', label: '1671', value: 1671, countryCode: 'GU' },
  { country: 'Guatemala', label: '502', value: 502, countryCode: 'GT' },
  { country: 'Guernsey', label: '44', value: 44, countryCode: 'GG' },
  { country: 'Guinea', label: '224', value: 224, countryCode: 'GN' },
  { country: 'Guinea-Bissau', label: '245', value: 245, countryCode: 'GW' },
  { country: 'Guyana', label: '592', value: 592, countryCode: 'GY' },
  { country: 'Haiti', label: '509', value: 509, countryCode: 'HT' },
  {
    country: 'Heard Island and Mcdonald Islands',
    label: '0',
    value: 0,
    countryCode: 'HM',
  },
  {
    country: 'Holy See (Vatican City State)',
    label: '379',
    value: 379,
    countryCode: 'VA',
  },
  { country: 'Honduras', label: '504', value: 504, countryCode: 'HN' },
  { country: 'Hong Kong', label: '852', value: 852, countryCode: 'HK' },
  { country: 'Hungary', label: '36', value: 36, countryCode: 'HU' },
  { country: 'Iceland', label: '354', value: 354, countryCode: 'IS' },
  { country: 'Indonesia', label: '62', value: 62, countryCode: 'ID' },
  {
    country: 'Iran, Islamic Republic of Persian Gulf',
    label: '98',
    value: 98,
    countryCode: 'IR',
  },
  { country: 'Iraq', label: '964', value: 964, countryCode: 'IQ' },
  { country: 'Ireland', label: '353', value: 353, countryCode: 'IE' },
  { country: 'Isle of Man', label: '44', value: 44, countryCode: 'IM' },
  { country: 'Israel', label: '972', value: 972, countryCode: 'IL' },
  { country: 'Italy', label: '39', value: 39, countryCode: 'IT' },
  { country: 'Jamaica', label: '1876', value: 1876, countryCode: 'JM' },
  { country: 'Japan', label: '81', value: 81, countryCode: 'JP' },
  { country: 'Jersey', label: '44', value: 44, countryCode: 'JE' },
  { country: 'Jordan', label: '962', value: 962, countryCode: 'JO' },
  { country: 'Kazakhstan', label: '7', value: 7, countryCode: 'KZ' },
  { country: 'Kenya', label: '254', value: 254, countryCode: 'KE' },
  { country: 'Kiribati', label: '686', value: 686, countryCode: 'KI' },
  {
    country: "Korea, Democratic People's Republic of Korea",
    label: '850',
    value: 850,
    countryCode: 'KP',
  },
  {
    country: 'Korea, Republic of South Korea',
    label: '82',
    value: 82,
    countryCode: 'KR',
  },
  { country: 'Kosovo', label: '383', value: 383, countryCode: 'XK' },
  { country: 'Kuwait', label: '965', value: 965, countryCode: 'KW' },
  { country: 'Kyrgyzstan', label: '996', value: 996, countryCode: 'KG' },
  { country: 'Laos', label: '856', value: 856, countryCode: 'LA' },
  { country: 'Latvia', label: '371', value: 371, countryCode: 'LV' },
  { country: 'Lebanon', label: '961', value: 961, countryCode: 'LB' },
  { country: 'Lesotho', label: '266', value: 266, countryCode: 'LS' },
  { country: 'Liberia', label: '231', value: 231, countryCode: 'LR' },
  {
    country: 'Libyan Arab Jamahiriya',
    label: '218',
    value: 218,
    countryCode: 'LY',
  },
  { country: 'Liechtenstein', label: '423', value: 423, countryCode: 'LI' },
  { country: 'Lithuania', label: '370', value: 370, countryCode: 'LT' },
  { country: 'Luxembourg', label: '352', value: 352, countryCode: 'LU' },
  { country: 'Macao', label: '853', value: 853, countryCode: 'MO' },
  { country: 'Macedonia', label: '389', value: 389, countryCode: 'MK' },
  { country: 'Madagascar', label: '261', value: 261, countryCode: 'MG' },
  { country: 'Malawi', label: '265', value: 265, countryCode: 'MW' },
  { country: 'Malaysia', label: '60', value: 60, countryCode: 'MY' },
  { country: 'Maldives', label: '960', value: 960, countryCode: 'MV' },
  { country: 'Mali', label: '223', value: 223, countryCode: 'ML' },
  { country: 'Malta', label: '356', value: 356, countryCode: 'MT' },
  { country: 'Marshall Islands', label: '692', value: 692, countryCode: 'MH' },
  { country: 'Martinique', label: '596', value: 596, countryCode: 'MQ' },
  { country: 'Mauritania', label: '222', value: 222, countryCode: 'MR' },
  { country: 'Mauritius', label: '230', value: 230, countryCode: 'MU' },
  { country: 'Mayotte', label: '262', value: 262, countryCode: 'YT' },
  { country: 'Mexico', label: '52', value: 52, countryCode: 'MX' },
  {
    country: 'Micronesia, Federated States of Micronesia',
    label: '691',
    value: 691,
    countryCode: 'FM',
  },
  { country: 'Moldova', label: '373', value: 373, countryCode: 'MD' },
  { country: 'Monaco', label: '377', value: 377, countryCode: 'MC' },
  { country: 'Mongolia', label: '976', value: 976, countryCode: 'MN' },
  { country: 'Montenegro', label: '382', value: 382, countryCode: 'ME' },
  { country: 'Montserrat', label: '1664', value: 1664, countryCode: 'MS' },
  { country: 'Morocco', label: '212', value: 212, countryCode: 'MA' },
  { country: 'Mozambique', label: '258', value: 258, countryCode: 'MZ' },
  { country: 'Myanmar', label: '95', value: 95, countryCode: 'MM' },
  { country: 'Namibia', label: '264', value: 264, countryCode: 'NA' },
  { country: 'Nauru', label: '674', value: 674, countryCode: 'NR' },
  { country: 'Nepal', label: '977', value: 977, countryCode: 'NP' },
  { country: 'Netherlands', label: '31', value: 31, countryCode: 'NL' },
  {
    country: 'Netherlands Antilles',
    label: '599',
    value: 599,
    countryCode: 'AN',
  },
  { country: 'New Caledonia', label: '687', value: 687, countryCode: 'NC' },
  { country: 'New Zealand', label: '64', value: 64, countryCode: 'NZ' },
  { country: 'Nicaragua', label: '505', value: 505, countryCode: 'NI' },
  { country: 'Niger', label: '227', value: 227, countryCode: 'NE' },
  { country: 'Nigeria', label: '234', value: 234, countryCode: 'NG' },
  { country: 'Niue', label: '683', value: 683, countryCode: 'NU' },
  { country: 'Norfolk Island', label: '672', value: 672, countryCode: 'NF' },
  {
    country: 'Northern Mariana Islands',
    label: '1670',
    value: 1670,
    countryCode: 'MP',
  },
  { country: 'Norway', label: '47', value: 47, countryCode: 'NO' },
  { country: 'Oman', label: '968', value: 968, countryCode: 'OM' },
  { country: 'Pakistan', label: '92', value: 92, countryCode: 'PK' },
  { country: 'Palau', label: '680', value: 680, countryCode: 'PW' },
  {
    country: 'Palestinian Territory, Occupied',
    label: '970',
    value: 970,
    countryCode: 'PS',
  },
  { country: 'Panama', label: '507', value: 507, countryCode: 'PA' },
  { country: 'Papua New Guinea', label: '675', value: 675, countryCode: 'PG' },
  { country: 'Paraguay', label: '595', value: 595, countryCode: 'PY' },
  { country: 'Peru', label: '51', value: 51, countryCode: 'PE' },
  { country: 'Philippines', label: '63', value: 63, countryCode: 'PH' },
  { country: 'Pitcairn', label: '64', value: 64, countryCode: 'PN' },
  { country: 'Poland', label: '48', value: 48, countryCode: 'PL' },
  { country: 'Portugal', label: '351', value: 351, countryCode: 'PT' },
  { country: 'Puerto Rico', label: '1939', value: 1939, countryCode: 'PR' },
  { country: 'Qatar', label: '974', value: 974, countryCode: 'QA' },
  { country: 'Romania', label: '40', value: 40, countryCode: 'RO' },
  { country: 'Russia', label: '7', value: 7, countryCode: 'RU' },
  { country: 'Rwanda', label: '250', value: 250, countryCode: 'RW' },
  { country: 'Reunion', label: '262', value: 262, countryCode: 'RE' },
  { country: 'Saint Barthelemy', label: '590', value: 590, countryCode: 'BL' },
  {
    country: 'Saint Helena, Ascension and Tristan Da Cunha',
    label: '290',
    value: 290,
    countryCode: 'SH',
  },
  {
    country: 'Saint Kitts and Nevis',
    label: '1869',
    value: 1869,
    countryCode: 'KN',
  },
  { country: 'Saint Lucia', label: '1758', value: 1758, countryCode: 'LC' },
  { country: 'Saint Martin', label: '590', value: 590, countryCode: 'MF' },
  {
    country: 'Saint Pierre and Miquelon',
    label: '508',
    value: 508,
    countryCode: 'PM',
  },
  {
    country: 'Saint Vincent and the Grenadines',
    label: '1784',
    value: 1784,
    countryCode: 'VC',
  },
  { country: 'Samoa', label: '685', value: 685, countryCode: 'WS' },
  { country: 'San Marino', label: '378', value: 378, countryCode: 'SM' },
  {
    country: 'Sao Tome and Principe',
    label: '239',
    value: 239,
    countryCode: 'ST',
  },
  { country: 'Saudi Arabia', label: '966', value: 966, countryCode: 'SA' },
  { country: 'Senegal', label: '221', value: 221, countryCode: 'SN' },
  { country: 'Serbia', label: '381', value: 381, countryCode: 'RS' },
  { country: 'Seychelles', label: '248', value: 248, countryCode: 'SC' },
  { country: 'Sierra Leone', label: '232', value: 232, countryCode: 'SL' },
  { country: 'Singapore', label: '65', value: 65, countryCode: 'SG' },
  { country: 'Slovakia', label: '421', value: 421, countryCode: 'SK' },
  { country: 'Slovenia', label: '386', value: 386, countryCode: 'SI' },
  { country: 'Solomon Islands', label: '677', value: 677, countryCode: 'SB' },
  { country: 'Somalia', label: '252', value: 252, countryCode: 'SO' },
  { country: 'South Africa', label: '27', value: 27, countryCode: 'ZA' },
  { country: 'South Sudan', label: '211', value: 211, countryCode: 'SS' },
  {
    country: 'South Georgia and the South Sandwich Islands',
    label: '500',
    value: 500,
    countryCode: 'GS',
  },
  { country: 'Spain', label: '34', value: 34, countryCode: 'ES' },
  { country: 'Sri Lanka', label: '94', value: 94, countryCode: 'LK' },
  { country: 'Sudan', label: '249', value: 249, countryCode: 'SD' },
  { country: 'Suriname', label: '597', value: 597, countryCode: 'SR' },
  {
    country: 'Svalbard and Jan Mayen',
    label: '47',
    value: 47,
    countryCode: 'SJ',
  },
  { country: 'Swaziland', label: '268', value: 268, countryCode: 'SZ' },
  { country: 'Sweden', label: '46', value: 46, countryCode: 'SE' },
  { country: 'Switzerland', label: '41', value: 41, countryCode: 'CH' },
  {
    country: 'Syrian Arab Republic',
    label: '963',
    value: 963,
    countryCode: 'SY',
  },
  { country: 'Taiwan', label: '886', value: 886, countryCode: 'TW' },
  { country: 'Tajikistan', label: '992', value: 992, countryCode: 'TJ' },
  {
    country: 'Tanzania, United Republic of Tanzania',
    label: '255',
    value: 255,
    countryCode: 'TZ',
  },
  { country: 'Thailand', label: '66', value: 66, countryCode: 'TH' },
  { country: 'Timor-Leste', label: '670', value: 670, countryCode: 'TL' },
  { country: 'Togo', label: '228', value: 228, countryCode: 'TG' },
  { country: 'Tokelau', label: '690', value: 690, countryCode: 'TK' },
  { country: 'Tonga', label: '676', value: 676, countryCode: 'TO' },
  {
    country: 'Trinidad and Tobago',
    label: '1868',
    value: 1868,
    countryCode: 'TT',
  },
  { country: 'Tunisia', label: '216', value: 216, countryCode: 'TN' },
  { country: 'Turkey', label: '90', value: 90, countryCode: 'TR' },
  { country: 'Turkmenistan', label: '993', value: 993, countryCode: 'TM' },
  {
    country: 'Turks and Caicos Islands',
    label: '1649',
    value: 1649,
    countryCode: 'TC',
  },
  { country: 'Tuvalu', label: '688', value: 688, countryCode: 'TV' },
  { country: 'Uganda', label: '256', value: 256, countryCode: 'UG' },
  { country: 'Ukraine', label: '380', value: 380, countryCode: 'UA' },
  {
    country: 'United Arab Emirates',
    label: '971',
    value: 971,
    countryCode: 'AE',
  },
  { country: 'United Kingdom', label: '44', value: 44, countryCode: 'GB' },
  { country: 'Uruguay', label: '598', value: 598, countryCode: 'UY' },
  { country: 'Uzbekistan', label: '998', value: 998, countryCode: 'UZ' },
  { country: 'Vanuatu', label: '678', value: 678, countryCode: 'VU' },
  {
    country: 'Venezuela, Bolivarian Republic of Venezuela',
    label: '58',
    value: 58,
    countryCode: 'VE',
  },
  { country: 'Vietnam', label: '84', value: 84, countryCode: 'VN' },
  {
    country: 'Virgin Islands, British',
    label: '1284',
    value: 1284,
    countryCode: 'VG',
  },
  {
    country: 'Virgin Islands, U.S.',
    label: '1340',
    value: 1340,
    countryCode: 'VI',
  },
  { country: 'Wallis and Futuna', label: '681', value: 681, countryCode: 'WF' },
  { country: 'Yemen', label: '967', value: 967, countryCode: 'YE' },
  { country: 'Zambia', label: '260', value: 260, countryCode: 'ZM' },
  { country: 'Zimbabwe', label: '263', value: 263, countryCode: 'ZW' },
];

export const PRODUCT_ORIENTATION = [
  { key: 'North', value: 0 },
  { key: 'East', value: 1 },
  { key: 'South', value: 2 },
  { key: 'West', value: 3 },
];

export const seriescolumnchart = [
  {
    name: 'Eanings this month',
    data: [355, 390, 300, 350, 390, 180, 355, 390],
  },
  {
    name: 'Expense this month',
    data: [280, 250, 325, 215, 250, 310, 280, 250],
  },
];
